### ISSUE TITLE
Voltage incorrect with Sunny Boy 2.0 inverter

### ISSUE THREAD

**Issue by SanderM2** [akabza/SMA_Modbus#1]
On a sunny boy 2.0 inverter the voltage is incorrect. 
I see this for example:
SerNo = ----------
PowerGrid = 0 W
CondMode =  307
OpHrs = 211.97 hrs
FeedInHrs = 210.03 hrs
TotalYield = 110.45 kWh
TotalGrid = 177.77 kWh
TotalFeedIn = 32.17 kWh
PowerGrid = 0 W
PowerFeed = 5187 W
PowerPV = 1311 W
U1 = 42949672.95 V
U2 = 42949672.95 V
U3 = 42949672.95 V

On my Tripower inverters the voltage is reported correctly.

**Comment by SanderM2** [comment]
It looks like the U1-U3 voltage is incorrect on the tripower too.
When I'm logged in to the SMA device the power is different (by 1V or so).

Searching online I found different modbus registers and I replaced:
    U1 = getvalue(31253, 2) / 100.0
    U2 = getvalue(31255, 2) / 100.0
    U3 = getvalue(31257, 2) / 100.0

with:

    U1 = getvalue(30783, 2) / 100.0
    U2 = getvalue(30785, 2) / 100.0
    U3 = getvalue(30787, 2) / 100.0


Now I get accurate reading from the tripower device and a correct U1 reading from the sunny boy inverter too.

**Comment by akabza** [comment]
Thanks for this comment. I updated the code today accordingly!
